name: Generate Pacman Contribution

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # This is the specialized Pacman Action
      - uses: jvns/github-contribution-pacman@master
        with:
          github_user_name: shivamtiwari01016
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated Real Pacman Maze" || echo "no changes"
          git push
